name: Manual Load Test with k6

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  # schedule:
  #   - cron: '*/15 5-17 * * *' # BKK 12:00 - 00:00
jobs:
  k6_load_test:
    name: k6 Load Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup k6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 test
        id: k6test
        uses: grafana/run-k6-action@v1
        with:
          path: loadtest.js

      - name: Generate Summary
        if: always()
        run: |
          if [ -f "summary.md" ]; then
            cat summary.md >> $GITHUB_STEP_SUMMARY
          else
            echo "## ❌ Error: summary.md not found" >> $GITHUB_STEP_SUMMARY
            echo "Check k6 console logs for errors." >> $GITHUB_STEP_SUMMARY
          fi

      - name: Log to Google Sheets
        if: always()
        run: |
          if [ -f "summary.json" ]; then
            curl -X POST -L "https://script.google.com/macros/s/AKfycbzg5DuvpiEbvfVBvwB7G91Nn0L_7tvLnOa4pTA4hfgui3YtC5GencRefWY_AwXHxOpD/exec" \
            -H "Content-Type: application/json" \
            -d @summary.json
          else
            echo "summary.json not found, skipping Google Sheets log."
          fi